name: Build Pipeline with AI Failure Explainer

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Setup do Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Rodar testes (com erro intencional)
        id: rodar_testes
        continue-on-error: true
        run: |
          python -m unittest tests/test_app.py > test_output.log 2>&1 || true

      - name: Explicar erro com IA (caso testes falhem)
        if: steps.rodar_testes.outcome == 'failure'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "⚠️ Testes falharam! Enviando log para IA..."

          TAIL_LOG=$(tail -n 20 test_output.log | sed 's/"/\\"/g' | tr '\n' '\\n')

          curl -s -X POST https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"gpt-4-o\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"Você é um especialista em CI/CD e testes Python.\"},
                {\"role\": \"user\", \"content\": \"O step de testes falhou com o seguinte log:\\n${TAIL_LOG}\\nExplique o erro de forma simples e sugira uma possível correção.\"}
              ]
            }" | jq '.choices[0].message.content'
